---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.15
        name: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: init-myservice
        image: bash
        command: ['bash', '-c', 'if [ ! -f "/workdir/index.html" ]; then echo Hello from minikube at $(date) > /workdir/index.html; fi']
        volumeMounts:
        - name: nginx-storage
          mountPath: /workdir
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  labels:
    app: nginx
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: Service
apiVersion: v1
metadata: 
  name: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: nginx
  type: LoadBalancer
